### PR TITLE
Change the q dependency version to latest stable

### PR DESCRIPTION
**Pull request by ghost**
@danactive, sorry I made a blunder in #10. Locally when i tested with q latest stable version 1.4.1 and before committing I took the latest version from https://david-dm.org/danactive/tfs-unlock instead of stable. In v2, they have [deprecated the `notify` property](https://github.com/kriskowal/q/blob/v2/CHANGES.md#202-warning-backward-incompatibility), which is causing the breakage at the moment. At some point we will need to update the code when v2 gets stable.

### CODE REVIEW

**Comment by danactive** [comment]
Oh no! Thx for the fix

**Comment by ghost** [comment]
Thanks! :tada: 
Can we get a new release? :)

**Comment by danactive** [comment]
Published to npm with v0.3.5

**Pull request merged**
