### PR TITLE
Updates dependencies' versions

### PR DESCRIPTION
**Pull request by ghost**
This PR updates the outdated dependencies' versions and uses circumflex accent character `^` ([compatible with version](https://docs.npmjs.com/files/package.json#dependencies)) for each dependency.

### CODE REVIEW

**Comment by danactive** [comment]
I'm no longer on a window machine, do the unit tests `npm test` still pass? Did you test the TFS commands?

**Comment by ghost** [comment]
> do the unit tests  npm test  still pass? Did you test the TFS commands?

Yup, and since this PR, I am using your package in production with this patch. :smile:

**Comment by danactive** [comment]
Great, thx. I'll npm publish this as v0.3.4 shortly

**Comment by ghost** [comment]
Thanks Dan! :+1: 
The most catchy feature in that release would be the VS2015 support! :sunglasses:

**Comment by danactive** [comment]
[Done](https://www.npmjs.com/package/tfs-unlock)

**Comment by ghost** [comment]
That's FAST! :tada:

**Pull request merged**
