### PR TITLE
Fixed unit test cases

### PR DESCRIPTION
**Pull request by mikejr83**
I fixed the unit test cases to pass. Status messages are passed out in status objects with the code and message. I also default the code to 0 if no code is returned in the result.

### CODE REVIEW

**Comment by mikejr83** [comment]
I also included another commit in this request to have the notify calls to the deferred promise bubble through the tfs commands. In other words you can now do

```
tfs.checkout(['somefile.txt']).then(handleResolve, handleReject, function(progress) {
  console.log(progress.index); //index in the array of files to be checked out
  console.log(progress.value.stream); // 'stdout' or 'stderr'
  console.log(progress.value.message); // what was sent to 'stdout' or 'stderr'
});
```

**Comment by mikejr83** [comment]
During my testing in my module which consumes this module I found a
    console.error
that was accidently checked in.

**Comment by danactive** [comment]
Thanks, the unit tests now pass. I bumped the version to v0.3.1 and published to npm

**Comment by mikejr83** [comment]
Thanks @danactive! Have you been using the plug-in much? I've been hoping for some feedback. I'm still running into odd issues on some of my teammates machines where they're getting odd errors. It's too bad that it's passing the "works on my machine" test.

**Comment by danactive** [comment]
No sorry, I no longer use TFS so I'm not able to contribute

**Comment by mikejr83** [comment]
Ok. If you have anyone report issues please let me know. Like I said, I'm still running into some oddball issues so I'm working on closing those out.

I'm actually migrating our system to TFS 2013 today. Hopefully I'll get these guys to go to git sooner than later!

**Pull request merged**
