### PR TITLE
VS 2017 unable to checkout

### PR DESCRIPTION
**Pull request by tribicito**

### CODE REVIEW

**Comment by tribicito** [comment]
[tfs-unlock.zip](https://github.com/danactive/tfs-unlock/files/839759/tfs-unlock.zip)

**Comment by danactive** [comment]
This looks like a trojan attempt

**Comment by tribicito** [comment]
Dan,

Is there a reason why this was flag as a trojan? I just zipped the file I changed and then upload it. I have an open ticket for this. It breaks when the machine only has VS 2017 installed.

**Comment by danactive** [comment]
The description for this pull request is empty, a zip file is a common delivery for suspicious files, and you are hijacking a branch created by greenkeeper. As you mention issue #14 this PR makes more sense. Please create a pull request from a forked repository using this [documentation](https://help.github.com/articles/creating-a-pull-request/)

**Pull request closed without merging**
